### ISSUE TITLE
Query regarding the use of `use_valedges_as_input` for Planetoid

### ISSUE THREAD

**Issue by venomouscyanide** [GraphPKU/NeuralCommonNeighbor#1]
Dear authors,

Thank you for sharing the code to your paper on NCN/NCNC.

I had a query regarding the use of `use_valedges_as_input` usage in your model in comparison to BUDDY/ELPH (Table 3 results). If I am not mistaken, the authors of BUDDY/ELPH indicate in their appendix that validation edges are also consumed as part of training message passing edges for both Planetoid and ogbl-collab datasets at the testing time. I am including a partial sentence indicating this:

"... but for the Planetoid and ogbl-collab datasets, the message passing edges at test time are the union of the training message passing edges and the validation supervision edges"

Taken from: Chamberlain, Benjamin Paul, et al. "Graph Neural Networks for Link Prediction with Subgraph Sketching." arXiv preprint arXiv:2209.15486 (2022).

Is there any reason NCN/NCNC does not use `use_valedges_as_input` for the Planetoid datasets runs?

Warm regards, 
Paul

**Comment by Xi-yuanWang** [comment]
Dear Paul.

Thank you for your interesting issue. We have yet to notice this difference. To our knowledge, "use_valedges_as_input" is a special option only for collab. 

However, it will not affect our conclusion significantly. `use_valedges_as_input` will generally boost all link prediction models. We will also include experiments with `use_valedges_as_input`.

Sincerely,
Xiyuan Wang

**Comment by venomouscyanide** [comment]
Hi Xiyuan,

Thank you for letting me know. I do admit that I am not 100% certain that the `use_valedges_as_input` has been applied to the Planetoid datasets in BUDDY/ELPH. However, thank you for the discussion and I am looking forward to your results!

Thank you again for sharing the codes and I found your paper very interesting, especially the discussions on TLR and CNC.

Warm regards, 
Paul

**Comment by venomouscyanide** [comment]
Marking as resolved. Thank you again for the discussions.
