### ISSUE TITLE
Code for neural common neighbor

### ISSUE THREAD

**Issue by voladorlu** [GraphPKU/NeuralCommonNeighbor#3]
Great thanks for opening the code, and sharing the new idea for link prediction task.

I tried to get the specific code for implementing neural common neighbor operation. But it seems not easy to target the right part. In the paper, neural common neighbor operator is based on the GNN representations of common neighbors. However, the train function in NeighborOverlap.py looks like missing the code for obtaining common neighbor representations before the predictor layer. Maybe I miss something important. Could you please give some hints to help me better understand the code?

Best

**Comment by Xi-yuanWang** [comment]
Hi,

We dynamically compute common neighbors in models' forward process rather than preprocessing.  Please refer to model.py/class CNLinkPredictor (line 582). 

Sincerely,
Xiyuan Wang

**Comment by voladorlu** [comment]
Thanks so much for your reply. I already go through the CNLinkPredictor. It seems that the code below might tell the answer. From the prediction function we can find that the number of common neighbors is used as an additional feature feeding to a linear layer. It looks like a little different from the description shown in the paper, which aggregates the node embeddings of common neighbors. Is there any special reason to do so? or probably I miss something important.

    ```
def multidomainforward(self,
                           x,
                           adj,
                           tar_ei,
                           filled1: bool = False,
                           cndropprobs: Iterable[float] = []):
        adj = self.dropadj(adj)
        xi = x[tar_ei[0]]
        xj = x[tar_ei[1]]
        cn = adjoverlap(adj, adj, tar_ei, filled1, cnsampledeg=self.cndeg)
        xcn = cn.sum(dim=-1).float().reshape(-1, 1)
        xij = self.xijlin(xi * xj)
        
        xs = torch.cat(
            [self.lin(self.xcnlin(xcn) * self.beta + xij)],
            dim=-1)
        return xs
```

**Comment by Xi-yuanWang** [comment]
You may misunderstand the code.

In CNLinkPredictor (around line 582). The code is
```
        adj = self.dropadj(adj)
        xi = x[tar_ei[0]]
        xj = x[tar_ei[1]]
        x = x + self.xlin(x)
        cn = adjoverlap(adj, adj, tar_ei, filled1, cnsampledeg=self.cndeg)
        xcns = [spmm_add(cn, x)]
        xij = self.xijlin(xi * xj)
        
        xs = torch.cat(
            [self.lin(self.xcnlin(xcn) * self.beta + xij) for xcn in xcns],
            dim=-1)
        return xs
```
which is just the same as our description.

The code piece you found may be from SCNLinkPredictor. SCNLinkPredictor is for GAE+CN in ablation study.

**Comment by voladorlu** [comment]
sorry for attaching the wrong code. Thanks for sharing the right one. That makes sense. -:)

Lu

best regards
