### ISSUE TITLE
Where are the NCN checkpoints of dataset ddi?

### ISSUE THREAD

**Issue by WEIYanbin1999** [GraphPKU/NeuralCommonNeighbor#7]
Dear Authors,

I notice NCNC uses NCN's checkpoints which you declare at the readme, however, these checkpoints are not available. After I run the code, I found there was a little performance degradation. Could you provide your checkpoints of DDI?

**Comment by Xi-yuanWang** [comment]
Dear Yanbin,

I did not keep it. So I retrained the model. I found that model's performance is quite unstable, so I change the number of epoch for training NCNC from 2 to 5. The checkpoints are in https://disk.pku.edu.cn/link/AA835A239DEF75441CB9B235D331296951.

Sincerely,
Xiyuan Wang

**Comment by WEIYanbin1999** [comment]
Dear Xiyuan,

Thanks for your quick reply. 

Best,
Yanbin
